# Styx config file !

pid_file = "./styx.pid"
bind_address = "0.0.0.0:8000"
shutdown_timeout = 3
cors_allowed_origins = ["*"]
http_read_buffer_size = 1048576
http_write_buffer_size = 1048576
tcp_read_buffer_size = 1048576
tcp_write_buffer_size = 1048576
tcp_timeout = 100

[log_manager]

data_directory = "./data"
write_buffer_size = 1048576

#[metrics.statsd]

#address = "127.0.0.1:8125"
#prefix = "styx" 