# Styx config file !

pid_file = "./data/nodeNUM/styx.pid"
bind_address = "127.0.0.1:800NUM"
shutdown_timeout = 3
cors_allowed_origins = ["*"]
http_read_buffer_size = 1048576
http_write_buffer_size = 1048576
http_longpoll_timeout = 10
http_max_longpoll_timeout = 100
tcp_read_buffer_size = 1048576
tcp_write_buffer_size = 1048576
tcp_timeout = 100

[log_manager]

data_directory = "./data/nodeNUM/logs"
write_buffer_size = 1048576

[node_manager]

node_name = "node1"
raft_directory = "./data/nodeNUM/raft"
# advertise_address = "127.0.0.1:800NUM"